name: Event Details on Issue
on: issues
jobs:
    event_details:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Print event details
              run: echo "${{ toJson(github.action) }}"