name: Event Details on Issue
on: issues
jobs:
    event_details:
        runs-on: ubuntu-latest
        steps:
            - name: Print event details
              run: echo "${{ toJson(github.event) }}"